---------------------------------------------------------------
-- Custom Events is triggered manully by this script object's Fire or BoardcastEvent function
-- arg1,arg2,arg3... ： event parameters in order
--------------------------------------------------------------